channels:
- anaconda-fusion
- defaults
dependencies:
- python=2.7
- mayavi
- mkl
- nbconvert
- nbformat
- numpy=1.13
- numpydoc
- pandas
- patsy
- pip
- pyqt
- qt
- scikit-learn
- scipy
- setuptools
- statsmodels
- seaborn
